# Generated by Django 2.2.4 on 2019-12-12 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(max_length=200, null=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('diaChiBDS', models.CharField(max_length=200, null=True)),
                ('dienTich', models.CharField(max_length=200, null=True)),
                ('dtsd', models.CharField(max_length=200, null=True)),
                ('feature', models.CharField(max_length=200, null=True)),
                ('geocoded', models.CharField(max_length=20, null=True)),
                ('gia', models.CharField(max_length=200, null=True)),
                ('image_uri', models.CharField(max_length=200, null=True)),
                ('khuVuc', models.CharField(max_length=200, null=True)),
                ('lat', models.CharField(max_length=200, null=True)),
                ('lienHe', models.CharField(max_length=200, null=True)),
                ('loaiTinRao', models.CharField(max_length=200, null=True)),
                ('long', models.CharField(max_length=200, null=True)),
                ('mota', models.CharField(max_length=200, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('name_unidecode', models.CharField(max_length=200, null=True)),
                ('ngayDang', models.CharField(max_length=200, null=True)),
                ('phongNgu', models.CharField(max_length=200, null=True)),
                ('phongTam', models.CharField(max_length=200, null=True)),
                ('project', models.CharField(max_length=200, null=True)),
                ('server', models.CharField(max_length=200, null=True)),
                ('spider', models.CharField(max_length=200, null=True)),
                ('tang', models.CharField(max_length=200, null=True)),
                ('tieuDe', models.CharField(max_length=200, null=True)),
                ('url', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('acreage', models.CharField(max_length=200, null=True)),
                ('internal_roads', models.CharField(max_length=200, null=True)),
                ('hxh', models.CharField(max_length=200, null=True)),
                ('hemxehoi', models.CharField(max_length=200, null=True)),
                ('area', models.CharField(max_length=200, null=True)),
                ('house_width', models.CharField(max_length=200, null=True)),
                ('bedrooms', models.IntegerField(null=True)),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('floors', models.CharField(max_length=200, null=True)),
                ('ground_floor', models.CharField(max_length=200, null=True)),
                ('terraces', models.CharField(max_length=200, null=True)),
                ('is_published', models.BooleanField(default=True, null=True)),
            ],
        ),
    ]
