# Generated by Django 2.2.4 on 2019-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='predict',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
