# Generated by Django 2.2.4 on 2019-12-13 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_predict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
