# Generated by Django 2.2.4 on 2019-12-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20191213_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_published',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
