# Generated by Django 2.2.4 on 2019-12-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20191213_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='diaChiBDS',
            new_name='diachibds',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='dienTich',
            new_name='dientich',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='khuVuc',
            new_name='khuvuc',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='lienHe',
            new_name='lienhe',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='loaiTinRao',
            new_name='loaitinrao',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='moTa',
            new_name='mota',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='ngayDang',
            new_name='ngaydang',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='phongNgu',
            new_name='phongngu',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='phongTam',
            new_name='phongtam',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='tieuDe',
            new_name='tieude',
        ),
    ]
