# Generated by Django 2.2.4 on 2020-01-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20191223_1136'),
        ('listings', '0007_auto_20191213_1026'),
        ('cases', '0005_auto_20191225_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='leads',
            field=models.ManyToManyField(related_name='cases_leads', to='leads.Lead'),
        ),
        migrations.AddField(
            model_name='case',
            name='listings',
            field=models.ManyToManyField(related_name='cases_listings', to='listings.Listing'),
        ),
    ]
