# Generated by Django 2.2.4 on 2020-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_auto_20200107_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(blank=True, choices=[('Question', 'Khách Hàng | Câu hỏi'), ('Đặt cọc', 'Khách Hàng | Đặt cọc'), ('Ký hợp đồng mua bán', 'Khách Hàng | Ký hợp đồng mua bán'), ('Sang tên', 'Khách Hàng | Sang tên sổ đỏ/hồng'), ('Problem', 'Khách Hàng | Vấn đề'), ('Hẹn lịch Xem Nhà', 'Chủ Nhà | Hẹn lịch Xem Nhà'), ('Thông tin về tranh chấp', 'Chủ Nhà | Thông tin về tranh chấp'), ('Sang tên sổ đỏ', 'Chủ Nhà | Sang tên sổ đỏ'), ('Ký hợp đồng môi giới', 'Chủ Nhà | Ký hợp đồng môi giới'), ('Giao tiền, giao giấy tờ', 'Chủ Nhà | Giao tiền, giao giấy tờ'), ('Thương lượng giá bán', 'Chủ Nhà | Thương lượng giá bán'), ('Thương lượng phí môi giới', 'Chủ Nhà | Thương lượng phí môi giới')], default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('Low', 'Thấp'), ('Normal', 'Bình thường'), ('High', 'Cao'), ('Urgent', 'Khẩn cấp')], max_length=64),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Mới'), ('Assigned', 'Assigned'), ('Pending', 'Đang xử lý'), ('Closed', 'Đóng'), ('Rejected', 'Từ chối'), ('Duplicate', 'Trùng lặp')], default='', max_length=64, null=True),
        ),
    ]
