# Generated by Django 2.2.4 on 2019-12-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20191223_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brokerage_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=12, null=True, verbose_name='commission Amount'),
        ),
    ]
