# Generated by Django 2.2.4 on 2019-12-23 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_user_brokerage_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_collaborator',
            field=models.BooleanField(default=False),
        ),
    ]
