# Generated by Django 2.2.4 on 2020-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0007_auto_20191223_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='Opportunity Amount'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='currency',
            field=models.CharField(blank=True, choices=[('VND', 'VND, Dong'), ('USD', '$, Dollar')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead_source',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('CALL', 'Cuộc gọi điện thoại'), ('EMAIL', ' EMAIL'), ('EXISTING CUSTOMER', 'Khách hàng hiện tại'), ('PARTNER', 'Đối tác'), ('PUBLIC RELATIONS', 'Quan hệ cộng đồng'), ('CAMPAIGN', 'Chiến dịch'), ('WEBSITE', 'WEBSITE'), ('OTHER', 'Khác')], max_length=255, null=True, verbose_name='Source of Lead'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('Lên lịch hẹn xem nhà', 'Lên lịch hẹn xem nhà (20%)'), ('Phân tích nhu cầu', 'Phân tích nhu cầu'), ('Đủ điều kiện để mua', 'Đủ điều kiện để mua (40%)'), ('Quyết định mua', 'Quyết định mua'), ('Có thể ký hợp đồng', 'Có thể ký hợp đồng (90%)'), ('Thương lượng giá', 'Thương lượng giá'), ('CLOSED WON', 'Closed won (100% Won)'), ('CLOSED LOST', 'Closed lost (0% Lost)')], max_length=64, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.CharField(blank=True, choices=[('New', 'Mới'), ('Assigned', 'Assigned'), ('Pending', 'Đang xử lý'), ('Closed', 'Đóng'), ('Rejected', 'Từ chối'), ('Duplicate', 'Trùng lặp')], default='', max_length=64, null=True),
        ),
    ]
