# Generated by Django 2.2.4 on 2020-01-10 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Low', 'Thấp'), ('Medium', 'Trung Bình'), ('High', 'Cao')], max_length=50, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('New', 'Mới'), ('In Progress', 'Đang xử lý'), ('Completed', 'Hoàn thành')], max_length=50, verbose_name='status'),
        ),
    ]
